# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16xAyMcGbCw5lC0NrmQVaAdPpWsXOlktk
"""

codigo = """
import streamlit as st
import sympy as sp

x = sp.symbols('x')

st.title("🎮 Arena da Derivação")

if "fase" not in st.session_state:
    st.session_state.fase = 1
    st.session_state.pontos = 0

fases = {
    1: (6*x**4 - 3*x**2 + 8*x - 5, 100),
    2: (x**3*(2*x-5), 200),
    3: ((x**2 + 4)/(x-1), 300),
    4: ((4*x**2 - 3*x + 1)**5, 400),
    5: ((x**2*(2*x+3)**4)/(3*x-2), 1000),
}

if st.session_state.fase <= 5:
    funcao, pontos = fases[st.session_state.fase]

    st.subheader(f"🔥 Fase {st.session_state.fase}")
    st.latex(sp.latex(funcao))

    resposta = st.text_input("Digite sua derivada:")

    if st.button("Enviar"):
        try:
            resposta_usuario = sp.sympify(resposta)
            derivada_correta = sp.diff(funcao, x)

            if sp.simplify(resposta_usuario - derivada_correta) == 0:
                st.success("✅ Correto! Próxima fase desbloqueada.")
                st.session_state.pontos += pontos
                st.session_state.fase += 1
            else:
                st.error("❌ Incorreto. Tente novamente.")
        except:
            st.warning("⚠️ Erro na expressão.")

    st.write("Pontuação:", st.session_state.pontos)

else:
    st.success("👑 Você derrotou o Algoritmo Supremo!")
    st.write("Pontuação final:", st.session_state.pontos)
"""

with open("app.py", "w") as f:
    f.write(codigo)

print("Arquivo app.py criado com sucesso!")